---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.PDF_GENERATOR_NAME}}"
spec:
  selector:
    matchLabels:
      name: "{{.PDF_GENERATOR_NAME}}"
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: "{{.PDF_GENERATOR_NAME}}"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: "{{.PDF_GENERATOR_NAME}}"
        image: "{{.PDF_GENERATOR_IMAGE}}:{{.PDF_GENERATOR_TAG}}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "4096Mi"
            cpu: "6000m"
          limits:
            memory: "4096Mi"
            cpu: "6000m"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{.PDF_GENERATOR_PORT}}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: {{.PDF_GENERATOR_PORT}}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        env:
          - name: KEYCLOAK_URI
            value: "{{.KEYCLOAK_PROTOCOL}}{{.KEYCLOAK_URL}}"
          - name: KEYCLOAK_REALM
            value: "{{.KEYCLOAK_REALM}}"
          - name: PDF_GENERATOR_KEYCLOAK_CLIENT_ID
            value: "{{.PDF_GENERATOR_KEYCLOAK_CLIENT_ID}}"
          - name: PDF_GENERATOR_ARENA_ACCESS_ROLES
            value: "{{.PDF_GENERATOR_ARENA_ACCESS_ROLES}}"
          - name: PDF_GENERATOR_KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{.PDF_GENERATOR_NAME}}"
                key: keycloakClientSecret
          - name: PDF_GENERATOR_KEYCLOAK_SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{.PDF_GENERATOR_NAME}}"
                key: keycloakSessionSecret
          - name: PDF_GENERATOR_PORT
            value: "{{.PDF_GENERATOR_PORT}}"
          - name: PDF_GENERATOR_LOG_LEVEL
            value: "{{.PDF_GENERATOR_LOG_LEVEL}}"
          - name: PDF_GENERATOR_AWS_S3_ENDPOINT
            value: "{{.PDF_GENERATOR_AWS_S3_ENDPOINT}}"
          - name: PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME
            value: "{{.PDF_GENERATOR_AWS_S3_PDF_BUCKETNAME}}"
          - name: PDF_GENERATOR_AWS_S3_ACCESS_KEY
            value: "{{.PDF_GENERATOR_AWS_S3_ACCESS_KEY}}"
          - name: PDF_GENERATOR_AWS_S3_PORT
            value: "{{.PDF_GENERATOR_AWS_S3_PORT}}"
          - name: PDF_GENERATOR_AWS_S3_PROTOCOL
            value: "{{.PDF_GENERATOR_AWS_S3_PROTOCOL}}"
          - name: PDF_GENERATOR_AWS_S3_REGION
            value: "{{.PDF_GENERATOR_AWS_S3_REGION}}"
          - name: PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER
            value: "{{.PDF_GENERATOR_CORRELATION_ID_REQUEST_HEADER}}"
          - name: PDF_GENERATOR_AWS_S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: "{{.PDF_GENERATOR_NAME}}"
                key: awsS3SecretKey
          - name: REDIS_PORT
            value: "{{.REDIS_PORT}}"
          - name: REDIS_SSL
            value: "{{.REDIS_SSL}}"
          - name: REDIS_URI
            value: "{{.REDIS_URL}}"
          - name: REDIS_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{.PDF_GENERATOR_NAME}}"
                key: redisToken
          - name: PDF_GENERATOR_ARENA_PORT
            value: "{{.PDF_GENERATOR_ARENA_PORT}}"
